on: [pull_request]

jobs:
  test:
    name: Evaluate Postgres Changes
    runs-on: ubuntu-latest
    steps:
      - name: data lineage check
        uses: grai-io/grai-actions/dbt@master
        with:
          namespace: "default"
          workspace: "188bec99-3f88-4c65-8bf0-a6787564a985"
          client-host: "api.grai.io"
          api-key: ${{ secrets.GRAI_API_KEY }}
          grai-frontend-host: "https://app.grai.io"
          db-host: sample-database.cudyk77thtpt.us-west-2.rds.amazonaws.com
          db-user: postgres
          db-password: jnicGnmRdXclhURSRr86
          db-database-name: jaffle_shop_dev
